language: c
sudo: required
dist: trusty
script: make lnvis
os:
  - linux
  - osx

env:
  global:
    - GLFW_VERSION=3.2.1
    - TRAVIS_CFLAGS="-I/home/travis/include"
    - TRAVIS_LDFLAGS="-L/home/travis/lib"
    - DISPLAY=:99.0

before_install:
  - ./.travis-setup.sh

addons:
  apt:
    packages:
      - &common_packages [ 'wget', 'unzip' ]
      - &build_packages [ 'cmake' ]
      - &mesa_packages [ 'libgl1-mesa-dev' ]
      - &x11_packages [
          'xorg-dev', 'libx11-dev', 'libxcursor-dev',
          'libxext-dev', 'libxi-dev', 'libxinerama-dev', 'libxrandr-dev',
          'libxss-dev', 'libxt-dev', 'libxv-dev', 'libxxf86vm-dev']

compiler:
- clang
- gcc
